Add troubleshooting instructions for installing Latin Modern fonts and Bugfix install_latin_modern_fonts.py script
cyrraz/plothist pull request #117
Opened 2024-02-06 07:01 UTC by 0ctagon

`install_latin_modern_fonts` was not correctly installing the fonts.
They were installed in `\~/.fonts/`, plus the unzip command was not working.
Added some documentation if the command is not recognize by the system (happened once).

2024-02-06 16:06 UTC, cyrraz approved these changes
I would propose to add 1.0.5->1.0.6 version change to this PR and make a new release.
The efficiency feature will need a bit more time.

2024-02-06 16:06 UTC, cyrraz commented on plothist/scripts/install_latin_modern_fonts.py
> +    Install Latin Modern fonts for matplotlib and clean the font cache.
clean -> clear

2024-02-06 16:09 UTC, cyrraz requested changes
See comments on my previous review.

2024-02-07 04:07 UTC, 0ctagon commented
@cyrraz  What do you think of removing the fonts section from `Style, fonts and colors` chapter and creating a `Fonts installation` chapter? The other one will only be `Style and colors`.

2024-02-07 08:43 UTC, cyrraz commented
> @cyrraz What do you think of removing the fonts section from `Style, fonts and colors` chapter and creating a `Fonts installation` chapter? The old chapter will be `Style and colors`. We can put this new chapter under `Utilities` or just below `Installation and update`

Yes, good idea.

2024-02-07 08:47 UTC, cyrraz requested changes
Could you please try to add a pytest to check that the font can be installed? I this is complicated, we may leave it for later.

2024-02-07 15:44 UTC, cyrraz approved these changes

2024-02-08 04:59 UTC, 0ctagon commented
I think this bugfix is too important to wait for a pytest to be implemented. The pytest will be added in a next PR.

2024-02-08 05:17 UTC, merged