Added side-by-side categorical hist plotting example
cyrraz/plothist pull request #153
Opened 2024-05-20 02:50 UTC by 0ctagon

Added this example, requested multiple times by users.

2024-05-21 08:05 UTC, cyrraz requested changes
Thanks for the PR, I wrote a couple of comments.

2024-05-21 08:05 UTC, cyrraz commented on docs/examples/1d_hist/1d_side_by_side.py
> +histo_arrays = [histo.values() for histo in histos]
This is bad practice because we loose information in that operation. We should keep working with the boost_histogram objects.

2024-05-22 04:50 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +import plothist  # For the style
We can discuss, for now I move it to Other complex examples section. I really like having this plot in the gallery, and it is much easier to do with boost-histogram than matplotlib.

2024-05-22 04:55 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +bin_width = 0.7
Yes, it has been tested (and it's very satisfying to test).

2024-05-22 04:57 UTC, 0ctagon commented on docs/img/1d_side_by_side.svg
Agreed

2024-05-22 04:57 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +ax.set_ylim(top=np.max([np.max(histo) for histo in histo_arrays]) + 2)
going with this solution for now.

2024-05-22 05:04 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +            height + 0.1,
Entry.
It turns out it is actually not needed, even for low bin values, the text is correctly placed on top of the bin.

2024-05-22 05:57 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +    # Optional: Add the number on top of each bar
Which unwanted results exactly? I get beautiful plots until N>10000, at this point the user can either increase the bin width, the figsize or write with some `10k` notation.

2024-05-22 06:03 UTC, 0ctagon commented on docs/examples/1d_hist/1d_side_by_side.py
> +            int(height),
For weighted histograms, it displays the weighted bin entries. The user only need to change the `ylabel` to `Weighted entries`, but he doesn't have to modify this `ax.text` section. What do you exactly mean by "This only works for an unweighted histogram"?

2024-05-22 06:18 UTC, 0ctagon commented
https://www.1001fonts.com/download/latin-modern-roman.zip seems down for the moment, so the pytests are failing.

2024-06-08 04:31 UTC, cyrraz commented on docs/examples/1d_hist/1d_side_by_side.py
> +            int(height),
I mean that we cast the height to int, which is wrong for a weighted histogram

2024-06-08 04:36 UTC, cyrraz approved these changes

2024-06-08 04:36 UTC, cyrraz commented on docs/examples/advanced/1d_side_by_side.py
> +            int(height),
We cannot assume height is a int in general (see answer in the thread), this is one reason why I wanted to remove this part, but this is minor, we could keep it, your call.

2024-06-08 04:36 UTC, cyrraz commented
@0ctagon Approved, but please check my comment before merging.

2024-06-10 03:11 UTC, merged