Add text upgrade
cyrraz/plothist pull request #154
Opened 2024-06-04 09:28 UTC by 0ctagon

Due to popular demand, more aliases have been added to the ``add_text`` function.
Only the ``bottom`` option is not retro-compatible, but it was really useless with its old value.

Documentation to see the table correctly here: https://plothist.readthedocs.io/en/add_text_upgrade/usage/utilities.html#add-text

2024-06-04 09:40 UTC, 0ctagon commented
Other examples of the positions:

![add_lumi](https://github.com/cyrraz/plothist/assets/43090327/b7cb8bf6-2da3-40ec-b86e-6ceb88ee2b5a)
![add_lumi_two_lines](https://github.com/cyrraz/plothist/assets/43090327/80a80d5a-c946-4dca-9d1b-df2a3caa5ee9)
![random_text_two_lines](https://github.com/cyrraz/plothist/assets/43090327/60dabc64-bae9-472b-89a8-fef9a31f3463)
![random_text](https://github.com/cyrraz/plothist/assets/43090327/a086944e-102e-406a-8d42-a69d6fc718d9)

2024-06-08 04:28 UTC, cyrraz requested changes
Cool feature, another time saver

2024-06-08 04:28 UTC, cyrraz commented on docs/advanced/model_examples.rst
> +    The function :func:`add_luminosity() <plothist.plothist_style.add_luminosity>` is used here to add information on the luminosity used for the data. This is common practice in high energy physics,
* luminosity -> integrated luminosity 
* Add link to https://en.wikipedia.org/wiki/Luminosity_(scattering_theory)
* Is it -> It is

2024-06-08 04:28 UTC, cyrraz commented on docs/examples/utility/add_text_example.py
> +        f"$\\mathtt{{add\\_text()}}$\n$\\mathtt{{x = {x_label}}}$\n$\\mathtt{{y = {y_label}}}$",
Add quotes around the arguments to show that they are string, as in 

https://plothist.readthedocs.io/en/latest/advanced/model_examples.html#all-the-different-comparisons

2024-06-08 04:28 UTC, cyrraz commented on docs/usage/utilities.rst
>  :func:`add_text() <plothist.plothist_style.add_text>` is a useful function to add text to a plot. It allows you to easily position a text either to the left or right and at the top or bottom of your
will ensure -> ensures
x and y parameters -> x and y positional parameters

2024-06-08 04:28 UTC, cyrraz commented on docs/usage/utilities.rst
> +     - Default ha
ha -> horizontal alignment

2024-06-08 04:28 UTC, cyrraz commented on docs/usage/utilities.rst
> +     - Default va
va -> vertical alignment

2024-06-08 04:28 UTC, cyrraz commented on docs/usage/utilities.rst
> +   * - ``left``
Add quotes around all the string parameters.

2024-06-08 04:28 UTC, cyrraz commented on docs/usage/utilities.rst
> +By default, the text also fit between the sub-plots by specifying the different axes, as shown in the example below:
fit -> fits

2024-06-08 04:28 UTC, cyrraz commented on src/plothist/plothist_style.py
>      None
Peaky, but add that is raises a value error in case of wrong alias

2024-06-10 04:46 UTC, cyrraz approved these changes

2024-06-10 06:05 UTC, merged