Replace wget and unzip
cyrraz/plothist pull request #176
Opened 2024-08-28 09:08 UTC by 0ctagon

Solve https://github.com/cyrraz/plothist/issues/175

2024-08-28 11:10 UTC, cyrraz commented on src/plothist/scripts/install_latin_modern_fonts.py
> +            open(f"{font_directory}/{url.split('/')[-1]}", "wb").write(r.content)
You forgot to close the file. Try this:
```
with (font_directory / url.split('/')[-1]).open("w") as f:
    f.write(r.content)
```

2024-08-28 11:13 UTC, cyrraz requested changes

2024-08-28 11:13 UTC, cyrraz commented on src/plothist/scripts/install_latin_modern_fonts.py
> +                print(f"Try {attempt + 1} of {max_attempt}\n {e}")
`{e}\n` should come at the beginning of the print

2024-08-29 02:03 UTC, 0ctagon commented
Let's make a small release after that for https://github.com/conda-forge/staged-recipes/pull/27414#event-14049744947

2024-08-29 02:24 UTC, cyrraz approved these changes

2024-08-29 02:24 UTC, merged