relative difference comparison
cyrraz/plothist pull request #49
Opened 2023-09-26 06:04 UTC by 0ctagon

2023-09-26 06:04 UTC, 0ctagon commented
Still needs a documentation update, but first lets check if everything is correct.

2023-10-03 08:28 UTC, 0ctagon commented
See: 
https://plothist.readthedocs.io/en/relative_difference/_images/1d_comparison_ratio.svg
https://plothist.readthedocs.io/en/relative_difference/_images/1d_comparison_relative_difference.svg
Same points, different uncertainties

2023-10-10 07:09 UTC, cyrraz requested changes

2023-10-10 08:00 UTC, 0ctagon commented
I don't remember if we want to remove the split option. It is still implemented.

2023-10-11 07:19 UTC, cyrraz requested changes

2023-10-11 07:19 UTC, cyrraz commented on plothist/plotters.py
>                      2 * h2_scaled_uncertainties, nan=2 * comparison_ylim[-1]
`nan = comparison_ylim[-1] - comparison_ylim[0]`

2023-10-11 07:20 UTC, cyrraz commented
> I don't remember if we want to remove the split option. It is still implemented.

We can keep it for now

2023-10-11 07:27 UTC, 0ctagon commented
Uncertainties are the same now:
https://github.com/cyrraz/plothist/blob/83f46a691c4c6d4cb45ef750c869f1d9218028a8/docs/img/1d_comparison_relative_difference.svg
https://github.com/cyrraz/plothist/blob/83f46a691c4c6d4cb45ef750c869f1d9218028a8/docs/img/1d_comparison_ratio.svg

2023-10-11 07:42 UTC, 0ctagon commented
HEP svg files changed because of the error bar display commit, but nothing changed visually.

2023-10-11 15:56 UTC, cyrraz approved these changes

2023-10-12 02:58 UTC, merged