Command line to install fonts
cyrraz/plothist pull request #52
Opened 2023-10-06 05:19 UTC by 0ctagon

Now the user just have to do `plothist_install_fonts` in his terminal (Linux or MacOS) to install plothist fonts.

2023-10-06 05:21 UTC, 0ctagon commented
The command line has to actually be checked manually. The function works, but idk for the command line in the pyproject.toml.

2023-10-10 07:09 UTC, cyrraz requested changes

2023-10-10 08:05 UTC, 0ctagon commented on pyproject.toml
> +plothist_install_fonts = "plothist.scripts.install_latin_modern_fonts:install_fonts"
This creates a {plothist_install_fonts` command that you can run on your terminal. If launched, it runs the `install_fonts()` function in `plothist/scripts/install_latin_modern_fonts.py`

2023-10-10 08:06 UTC, 0ctagon commented on plothist/scripts/install_latin_modern_fonts.py
> +        __name__, "install_latin_modern_fonts.sh"
As discussed, I'll leave it to you.

2023-10-13 12:21 UTC, cyrraz commented on plothist/scripts/install_latin_modern_fonts.py
> +        __name__, "install_latin_modern_fonts.sh"
Done

2023-10-13 12:26 UTC, cyrraz commented
Hi @0ctagon, please have a look at this update. If it is fine with you, let's merge it. Please ask a macOS user in the office to test it.

2023-10-13 12:26 UTC, cyrraz approved these changes

2023-10-16 06:18 UTC, 0ctagon commented
You can merge and do the test version in PyPI to check if everything works. If yes, we can put it in v0.8 with the complex 2D plot.

2023-10-16 06:57 UTC, cyrraz approved these changes

2023-10-16 06:57 UTC, cyrraz commented on plothist/scripts/install_latin_modern_fonts.py
> +    except subprocess.CalledProcessError:
I think so

2023-10-16 06:58 UTC, merged