Variable registry update
cyrraz/plothist pull request #69
Opened 2023-11-21 07:31 UTC by 0ctagon

This PR adds a lot of functionality to the variable registry.

2023-11-21 12:03 UTC, cyrraz requested changes

2023-11-21 12:06 UTC, cyrraz commented on plothist/variable_registry.py
> +            try:
Or better:

```
if variable_registry[variable_key].pop(parameter, None) is None:
    warnings.warn(f"{parameter} not present in the registry for {variable_key}, skipping.")
```

2023-11-22 02:59 UTC, 0ctagon commented on plothist/variable_registry.py
> +            try:
I thonk copilot learnt to much ROOT...

2023-11-22 06:48 UTC, cyrraz requested changes

2023-11-22 06:48 UTC, cyrraz commented on plothist/variable_registry.py
> +    variable_keys,
`=None`

2023-11-22 06:48 UTC, cyrraz commented on plothist/variable_registry.py
> +        try:
Why not `if "bins" in variable.keys() and "range" in variable.keys():`

2023-11-22 06:48 UTC, cyrraz commented on plothist/variable_registry.py
> +    dictionary, variable_keys, path="./variable_registry.yaml", overwrite=False
`variable_keys=None`

2023-11-22 08:04 UTC, cyrraz approved these changes

2023-11-22 08:55 UTC, merged